### ISSUE TITLE
Upload dSYM to Crashlytics in fastlane

### ISSUE THREAD

**Issue by nwingt** [likecoin/likecoin-app#108]

**Comment by williamchong007** [comment]
fastlane has `download_dsyms` and `upload_symbols_to_crashlytics` task for this job. We would need to wait for `build processing` in `upload_to_testflight` though, otherwise the dsym would not be available for download yet.

Since waiting for build process would be too long in CI, maybe we need another trigger for this dsym lane

**Comment by nwingt** [comment]
How about using tag in master branch?

**Comment by nwingt** [comment]
Resolved in 8d09bc8759b005152a6f96d099d625116cba12d2
